//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemQuanLyNhanKhau
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoKhau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoKhau()
        {
            this.NhanKhauTamVangs = new HashSet<NhanKhauTamVang>();
            this.NhanKhauTamTrus = new HashSet<NhanKhauTamTru>();
            this.NhanKhauThuongTrus = new HashSet<NhanKhauThuongTru>();
        }
    
        public string MaSoHoKhau { get; set; }
        public string SoNha { get; set; }
        public string Duong { get; set; }
        public string Phuong { get; set; }
        public string Quan { get; set; }
        public string ThanhPho { get; set; }
        public string ChuHo { get; set; }
    
        public virtual CaNhan CaNhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanKhauTamVang> NhanKhauTamVangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanKhauTamTru> NhanKhauTamTrus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanKhauThuongTru> NhanKhauThuongTrus { get; set; }
    }
}
