//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemQuanLyNhanKhau
{
    using System;
    using System.Collections.Generic;
    
    public partial class KT3
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KT3()
        {
            this.NhanKhauTamTrus = new HashSet<NhanKhauTamTru>();
        }
    
        public string MaSoKT3 { get; set; }
        public string ChuSoKT3 { get; set; }
        public Nullable<System.DateTime> NgayCapSo { get; set; }
    
        public virtual CaNhan CaNhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanKhauTamTru> NhanKhauTamTrus { get; set; }
    }
}
