//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemQuanLyNhanKhau
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanKhauThuongTru
    {
        public string NguoiThuongTru { get; set; }
        public string QuanHeVoiChuHo { get; set; }
        public Nullable<System.DateTime> NgayDKTHTR { get; set; }
        public string ThongTinHoKhau { get; set; }
        public string GhiChu { get; set; }
    
        public virtual CaNhan CaNhan { get; set; }
        public virtual HoKhau HoKhau { get; set; }
    }
}
